import Navigation from "@components/core/navigation";
import { i18n, Locale } from "@lib/i18n";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const { lang } = params;

  // favicon shows up as static prop...
  // @ts-ignore
  if (lang === "favicon.ico") {
    return (
      <>
        <body></body>
      </>
    );
  }

  return (
    <html lang={lang}>
      <body>
        <Navigation lang={lang} />
        {children}
      </body>
    </html>
  );
}
