name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DIGITALOCEAN_REGISTRY_USERNAME: ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }}
  DIGITALOCEAN_REGISTRY_PASSWORD: ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Set tag with commit SHA
        run: |
          DOCKER_TAG=af-nextjs-blog:${{ github.sha }}
          echo "::set-env name=DOCKER_TAG::$DOCKER_TAG"

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_TAG .
          docker tag $DOCKER_TAG registry.digitalocean.com/af-nextjs-blog/$DOCKER_TAG

      - name: Login to DigitalOcean registry
        run: echo $DIGITALOCEAN_REGISTRY_PASSWORD | docker login -u $DIGITALOCEAN_REGISTRY_USERNAME --password-stdin registry.digitalocean.com

      - name: Push Docker image to registry
        run: docker push registry.digitalocean.com/af-nextjs-blog/$DOCKER_TAG
