name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DIGITALOCEAN_REGISTRY_USERNAME: ${{ secrets.DIGITALOCEAN_REGISTRY_USERNAME }}
  DIGITALOCEAN_REGISTRY_PASSWORD: ${{ secrets.DIGITALOCEAN_REGISTRY_PASSWORD }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Build Docker image
        run: |
          docker build -t af-nextjs-blog:${GITHUB_SHA} .
          docker tag af-nextjs-blog:${GITHUB_SHA} registry.digitalocean.com/af-nextjs-blog/af-nextjs-blog:${GITHUB_SHA}

      - name: Login to DigitalOcean registry
        run: echo $DIGITALOCEAN_REGISTRY_PASSWORD | docker login -u $DIGITALOCEAN_REGISTRY_USERNAME --password-stdin registry.digitalocean.com

      - name: Push Docker image to registry
        run: docker push registry.digitalocean.com/af-nextjs-blog/af-nextjs-blog:${GITHUB_SHA}
